### ISSUE TITLE
create project fails on company vpn

### ISSUE THREAD

**Issue by psaraf** [microsoft/vscode-spring-initializr#137]
Get below error by maven if using in vpn 
Unable to get local issuer certificate

**Comment by Eskibear** [comment]
This extension sends request to `https://start.spring.io/` by default. Let's track the networking issue in https://github.com/microsoft/vscode-spring-initializr/issues/101, and see if you can get any help from current discussion. 

Per your networking status, you might work it around by change `serviceUrl` to use `http` instead of `https`, but it's not recommended. The ideal solution would be to contact your company IT.
