### ISSUE TITLE
Unable to use number in the Group Id after first dot

### ISSUE THREAD

**Issue by craph** [microsoft/vscode-spring-initializr#198]
Hello,

I open this issue because I'm unable to use number in the GroupId input field when I run the Spring Initializr.

Is it normal ?

![image](https://user-images.githubusercontent.com/14820052/153865597-9df614e7-f091-4212-97d7-45d17b0a2b4c.png)
We should be able to use numbers in GroupId just after the first dot !

Thank you very much.
Best regards,

**Comment by Eskibear** [comment]
> If any of the resulting package name components start with a digit, or any other character that is not allowed as an initial character of an identifier, have an underscore prefixed to the component.

According to Maven's official docs, component should not start with a digit. See below: 
https://maven.apache.org/guides/mini/guide-naming-conventions.html 
https://docs.oracle.com/javase/specs/jls/se6/html/packages.html#7.7

And that's why we implement current validation logic as below:

https://github.com/microsoft/vscode-spring-initializr/blob/ed2fc6e47f2d3bfb2b775d842e3d906d640e262a/src/Utils/index.ts#L109-L111

**Comment by Eskibear** [comment]
Thank you for clarifying the docs. I'm ok with it. 

But to change one `*` to `+` because we don't expect any empty subgroup like `com..example`
```
/^[a-z_][a-z0-9_]*(\.[a-z0-9_]+)*$/
```

**Comment by craph** [comment]
Hello @Eskibear ,

I just pushed a PR about this issue.
