### ISSUE TITLE
Specify Spring Boot version bug in the initializr

### ISSUE THREAD

**Issue by MargarytaChepiga** [Microsoft/vscode-spring-initializr#84]
Hi there!

I am not sure if it's a bug or not, I just installed Spring Boot Extension Pack and it's my first time using it.
The issue I am having is that I cannot pass the 'Specify Spring Boot version' when using Spring initializr. 

Please see the gif below:

![oct-16-2018 14-23-39](https://user-images.githubusercontent.com/15698572/47038353-3f55a880-d14f-11e8-95e6-f626030b63db.gif)

There is nothing said about it in the Configuration too:

<img width="728" alt="screen shot 2018-10-16 at 2 26 06 pm" src="https://user-images.githubusercontent.com/15698572/47038449-86439e00-d14f-11e8-9f60-d59317747313.png">

1) Am I doing something wrong? What is the expected input?
2) Is it a bug? If yes, how I should proceed about it as a user?

I would really appreciate any help with this, thank you in advance!

**Comment by Eskibear** [comment]
I cannot reproduce the issue here. By design, it will fetch a list of available boot versions according to the service URL, and you can pick up one from the list. It looks more like a networking issue. Can you try the following?

1. Open https://start.spring.io/  in your browser, see if it works well. 
2. Check if there's any networking related configuration in your settings. e.g. proxy

**Comment by MargarytaChepiga** [comment]
Thank you @Eskibear for such a quick response!
I tried https://start.spring.io/, and it works perfectly.
I guess it is proxy issue actually.
